"""empty message

Revision ID: 680bc219ed39
Revises: 82b7d8122309
Create Date: 2025-06-26 08:33:26.896781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680bc219ed39'
down_revision = '82b7d8122309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_sign', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=False),
    sa.Column('current_longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sign')
    )
    op.create_table('incident_ground_unit_association',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('ground_unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ground_unit_id'], ['ground_unit.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'ground_unit_id')
    )
    with op.batch_alter_table('drone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_feed_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drone', schema=None) as batch_op:
        batch_op.drop_column('video_feed_url')

    op.drop_table('incident_ground_unit_association')
    op.drop_table('ground_unit')
    # ### end Alembic commands ###
