"""Add location columns to Drone table

Revision ID: f6d023725db4
Revises: e27fb4bb1543
Create Date: 2025-06-21 08:23:58.963895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d023725db4'
down_revision = 'e27fb4bb1543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('current_longitude', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drone', schema=None) as batch_op:
        batch_op.drop_column('current_longitude')
        batch_op.drop_column('current_latitude')

    # ### end Alembic commands ###
